### ISSUE TITLE
Security policy

### ISSUE THREAD

**Issue by ks0777** [NicolasSegl/Hermes#1]
Hi, I found a vulnerability in your emulator but could not find a way of contacting you since you have not defined a security policy. I realize this is a hobby project, but would like to see this resolved. I can gladly give you more details on the vulnerability and its impact if you enable private vulnerability reports (https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) or tell me how I can contact you.

**Comment by NicolasSegl** [comment]
Thank you so much for reaching out. I have enabled the private vulnerability reports.
